### ISSUE TITLE
How do I define a user as an administrator?

### ISSUE THREAD

**Issue by rafaelsabino** [sgezel/pronostiek#1]
I would like to know how I define a user as an administrator

**Comment by rafaelsabino** [comment]
Someone?

**Comment by sgezel** [comment]
Hi, you can edit the user JSON and add admin:true to the user object.

ie:
`{
  "username":"user@mail.com",
  "name":"user",
  "admin":"true",
  "password":"123456"
}`

Do note this is a quick and dirty solution :-)
